Comment mapper test new
AkademiaProgramowania/educators-back pull request #31
Opened 2023-07-06 15:26 UTC by PrzemyslawGromiec

updated working tests and CommentMapper class

2023-07-07 21:17 UTC, DrJul requested changes

2023-07-07 21:17 UTC, DrJul commented on src/test/java/com/akademia/educators_back/mapper/CommentMapperTest.java
> +public class CommentMapperTest {
w testach nie trzeba pisać słowa public zarówno w samej klasie jak i poszczególnych testach - Intelli podkreśla to też, usuń proszę

2023-07-07 21:52 UTC, PrzemyslawGromiec commented on src/test/java/com/akademia/educators_back/mapper/CommentMapperTest.java
> +public class CommentMapperTest {
nie zauwazylem, juz poprawione

2023-07-10 18:02 UTC, DrJul approved these changes

2023-07-10 18:02 UTC, merged